#! /bin/bash
#
# Tries to install a package. 
# 
# Arguments:
# $1: package name in code.grnet.gr
# $2: installation folder

if [ ! -e $SNF_HOME/"$1" ]; then
	git clone https://code.grnet.gr/git/"$1" $SNF_HOME/"$2"
fi
if [ -z "`command -v "$2"`" ]; then
	cd $SNF_HOME/"$2"
	./setup.py build
	./setup.py install 2>install.err
	if [ -n "`grep "error" install.err`" ]; then
		rm "`command -v "$2"`"
		echo "${txtred}The "$2" tool could not be installed."
		echo "Please consult the ${SNF_HOME}/"$2"/install.err file.${txtrst}"
		#exit 1
	else
		echo "${txtgrn}The "$2" tool has been installed${txtrst}"
		#rm install.err
	fi
		
else
	echo "${txtgrn}The "$2" tool has already been installed${txtrst}"
fi
return 0
